import React, { useState, useEffect } from 'react';
import {
  X,
  Save,
  MessageSquare,
  Sparkles,
  Trophy,
  CheckCircle2,
  GraduationCap,
  Wand2,
  ThumbsUp,
  AlertTriangle,
  RotateCcw,
} from 'lucide-react';
import {
  GroupSummary,
  GroupWeeklyRemark,
  OfficerWeeklyRemarks,
  Student,
  StudentWeeklyRecord,
} from '../types/discipline';
import {
  generateAutoTeacherRemarkForGroup,
  generateAutoTeacherRemarksForAllGroups,
} from '../utils/autoRemarks';

interface TeacherGroupNotesModalProps {
  isOpen: boolean;
  onClose: () => void;
  currentWeekName: string;
  currentWeekId: number;
  groups: GroupSummary[];
  teacherGroupNotes: Record<number, string>;
  groupRemarks?: Record<number, GroupWeeklyRemark>;
  officerRemarks?: OfficerWeeklyRemarks;
  students?: Student[];
  records?: Record<string, StudentWeeklyRecord>;
  onSaveTeacherGroupNotes: (updatedNotes: Record<number, string>) => void;
}

const QUICK_NOTE_TEMPLATES = [
  '🎁 Biểu dương nhóm xếp hạng 1 nhận phần thưởng thi đua tuần!',
  '🌟 Biểu dương nhóm thi đua xuất sắc, phát biểu sôi nổi.',
  '⚠️ Nhắc nhở: Học sinh vi phạm nghiêm trọng sẽ bị xử lý theo nội quy của lớp.',
  '📖 Cần tăng cường truy bài 15p đầu giờ và làm bài tập về nhà.',
  '👔 Nhắc nhở cả nhóm chú ý khăn quàng đỏ và đồng phục nghiêm túc.',
  '⏰ Nhắc nhở các bạn đi học đúng giờ, không đi trễ tiết chiều.',
  '🧹 Đề nghị nhóm làm trực nhật cẩn thận, lau bảng sạch sẽ.',
  '🎯 Phát huy tinh thần tự giác, kèm cặp giúp đỡ các bạn còn yếu.',
];

export const TeacherGroupNotesModal: React.FC<TeacherGroupNotesModalProps> = ({
  isOpen,
  onClose,
  currentWeekName,
  currentWeekId,
  groups,
  teacherGroupNotes,
  groupRemarks = {},
  officerRemarks,
  students = [],
  records = {},
  onSaveTeacherGroupNotes,
}) => {
  const [notes, setNotes] = useState<Record<number, string>>({});
  const [savedSuccess, setSavedSuccess] = useState(false);
  const [autoGeneratedNotice, setAutoGeneratedNotice] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen) {
      setNotes({ ...teacherGroupNotes });
      setSavedSuccess(false);
      setAutoGeneratedNotice(null);
    }
  }, [isOpen, teacherGroupNotes]);

  if (!isOpen) return null;

  const handleNoteChange = (groupId: number, value: string) => {
    setNotes((prev) => ({
      ...prev,
      [groupId]: value,
    }));
  };

  const handleApplyTemplate = (groupId: number, template: string) => {
    setNotes((prev) => {
      const current = prev[groupId]?.trim() || '';
      const updated = current ? `${current}; ${template}` : template;
      return {
        ...prev,
        [groupId]: updated,
      };
    });
  };

  // Tự động nhận xét cho 1 nhóm dựa trên báo cáo tuần
  const handleAutoGenerateForGroup = (groupId: number) => {
    const group = groups.find((g) => g.groupId === groupId) || {
      groupId,
      groupName: `Nhóm ${groupId}`,
      leaderName: groupRemarks[groupId]?.leaderName || `Nhóm trưởng ${groupId}`,
      studentCount: 7,
      averageScore: 100,
      totalBonus: 0,
      totalPenalty: 0,
      rank: groupId,
      topStudents: [],
      studentsNeedingImprovement: [],
    };

    const autoRemark = generateAutoTeacherRemarkForGroup({
      group,
      groupRemark: groupRemarks[groupId],
      officerRemarks,
      students,
      records,
    });

    setNotes((prev) => ({
      ...prev,
      [groupId]: autoRemark,
    }));
    setAutoGeneratedNotice(`Đã tạo nhận xét tự động theo báo cáo cho Nhóm ${groupId}!`);
    setTimeout(() => setAutoGeneratedNotice(null), 3000);
  };

  // Tự động nhận xét cho toàn bộ 6 nhóm dựa trên báo cáo tuần
  const handleAutoGenerateAll = () => {
    const autoRemarks = generateAutoTeacherRemarksForAllGroups({
      groups,
      groupRemarks,
      officerRemarks,
      students,
      records,
    });

    setNotes(autoRemarks);
    setAutoGeneratedNotice('Đã tự động tạo nhận xét theo báo cáo tuần cho toàn bộ 6 nhóm!');
    setTimeout(() => setAutoGeneratedNotice(null), 3500);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSaveTeacherGroupNotes(notes);
    setSavedSuccess(true);
    setTimeout(() => {
      setSavedSuccess(false);
      onClose();
    }, 600);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col overflow-hidden my-auto animate-in fade-in zoom-in-95 duration-150">
        {/* Header (Cố định ở trên) */}
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-slate-200 bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-400 text-slate-950 flex items-center justify-center font-bold shadow-md shrink-0">
              <GraduationCap className="w-5 h-5 text-slate-950" />
            </div>
            <div>
              <h3 className="text-base font-extrabold text-white flex items-center gap-2">
                <span>Ghi Chú & Nhận Xét Của GVCN Cho 6 Nhóm</span>
                <span className="text-xs px-2 py-0.5 rounded-full bg-indigo-500/30 text-amber-300 border border-amber-400/30 font-bold">
                  {currentWeekName}
                </span>
              </h3>
              <p className="text-xs text-indigo-200 mt-0.5">
                Tự động nhận xét theo báo cáo tuần của Nhóm trưởng, Ban cán sự và thi đua
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body cuộn mượt mà */}
        <form onSubmit={handleSubmit} className="flex flex-col flex-1 overflow-hidden min-h-0">
          <div className="overflow-y-auto flex-1 p-5 space-y-4">
            {/* Thanh công cụ: Tự động nhận xét cả 6 nhóm theo báo cáo */}
            <div className="p-3.5 bg-gradient-to-r from-emerald-50 via-teal-50 to-indigo-50 border border-emerald-200 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-2xs">
              <div className="flex items-start gap-2.5">
                <Sparkles className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                <div>
                  <h4 className="text-xs font-bold text-emerald-950">
                    Nhận xét tự động thông minh theo báo cáo tuần
                  </h4>
                  <p className="text-[11px] text-emerald-800 leading-relaxed mt-0.5">
                    Hệ thống sẽ tổng hợp báo cáo Ưu/Khuyết điểm từ Nhóm trưởng, lỗi vi phạm, điểm thi đua và nhận xét Ban cán sự để tạo lời dặn dò chuẩn sư phạm cho từng nhóm.
                  </p>
                </div>
              </div>

              <button
                type="button"
                onClick={handleAutoGenerateAll}
                className="flex items-center justify-center gap-2 px-3.5 py-2 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 active:from-emerald-800 text-white font-black text-xs rounded-xl shadow-md border border-emerald-400/40 transition-all cursor-pointer hover:scale-[1.02] shrink-0"
                title="Bấm để tự động phân tích báo cáo và điền nhận xét sư phạm cho toàn bộ 6 nhóm"
              >
                <Wand2 className="w-4 h-4 text-amber-300 animate-bounce" />
                <span>Tự động nhận xét cả 6 nhóm</span>
              </button>
            </div>

            {/* Thông báo khi tạo nhận xét tự động */}
            {autoGeneratedNotice && (
              <div className="p-2.5 bg-indigo-50 border border-indigo-200 rounded-xl text-xs font-bold text-indigo-900 flex items-center gap-2 animate-in fade-in">
                <CheckCircle2 className="w-4 h-4 text-indigo-600 shrink-0" />
                <span>{autoGeneratedNotice}</span>
              </div>
            )}

            {/* Danh sách 6 nhóm */}
            <div className="space-y-3.5">
              {[1, 2, 3, 4, 5, 6].map((groupId) => {
                const group = groups.find((g) => g.groupId === groupId);
                const currentNote = notes[groupId] || '';
                const rank = group?.rank || groupId;
                const avg = group?.averageScore || 100;
                const grReport = groupRemarks[groupId];

                return (
                  <div
                    key={groupId}
                    className="p-4 rounded-xl border border-slate-200 bg-slate-50/70 hover:bg-white hover:border-indigo-300 transition-all space-y-2.5 shadow-2xs"
                  >
                    {/* Header thông tin nhóm */}
                    <div className="flex items-center justify-between flex-wrap gap-2">
                      <div className="flex items-center gap-2.5">
                        <span className="w-7 h-7 rounded-lg bg-indigo-600 text-white font-black text-xs flex items-center justify-center shadow-xs">
                          {groupId}
                        </span>
                        <div>
                          <h4 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                            <span>{group?.groupName || `Nhóm ${groupId}`}</span>
                            <span className="text-[11px] font-semibold text-slate-500">
                              (Nhóm trưởng: {group?.leaderName || 'Đang cập nhật'})
                            </span>
                          </h4>
                        </div>
                      </div>

                      <div className="flex items-center gap-2 text-xs">
                        <span className="px-2 py-0.5 rounded-md font-bold bg-amber-100 text-amber-900 border border-amber-200">
                          Hạng {rank}
                        </span>
                        <span className="font-mono font-bold text-slate-800">
                          TB: {avg}đ
                        </span>

                        {/* Nút tự động nhận xét riêng cho nhóm này */}
                        <button
                          type="button"
                          onClick={() => handleAutoGenerateForGroup(groupId)}
                          className="flex items-center gap-1 px-2.5 py-1 bg-white hover:bg-emerald-50 text-emerald-700 hover:text-emerald-800 border border-emerald-300 rounded-lg text-[11px] font-bold shadow-2xs transition-colors cursor-pointer"
                          title="Tự động tạo nhận xét sư phạm theo báo cáo của Nhóm này"
                        >
                          <Sparkles className="w-3 h-3 text-emerald-600" />
                          <span>Tự động nhận xét</span>
                        </button>
                      </div>
                    </div>

                    {/* Tóm tắt báo cáo của Nhóm trưởng nếu có */}
                    {grReport && (grReport.pros || grReport.cons || grReport.exemplaryStudent || grReport.remindStudent) && (
                      <div className="bg-white p-2.5 rounded-lg border border-slate-200 text-[11px] space-y-1">
                        <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block">
                          Báo cáo từ Nhóm trưởng {grReport.leaderName}:
                        </span>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 text-slate-700">
                          {grReport.pros && (
                            <p className="flex items-start gap-1">
                              <span className="text-emerald-600 font-bold shrink-0">✓ Ưu điểm:</span>
                              <span className="truncate">{grReport.pros}</span>
                            </p>
                          )}
                          {grReport.cons && (
                            <p className="flex items-start gap-1">
                              <span className="text-rose-600 font-bold shrink-0">✗ Tồn tại:</span>
                              <span className="truncate">{grReport.cons}</span>
                            </p>
                          )}
                          {grReport.exemplaryStudent && (
                            <p className="flex items-start gap-1">
                              <span className="text-amber-600 font-bold shrink-0">⭐ Biểu dương:</span>
                              <span className="truncate">{grReport.exemplaryStudent}</span>
                            </p>
                          )}
                          {grReport.remindStudent && (
                            <p className="flex items-start gap-1">
                              <span className="text-indigo-600 font-bold shrink-0">⚠️ Nhắc nhở:</span>
                              <span className="truncate">{grReport.remindStudent}</span>
                            </p>
                          )}
                        </div>
                      </div>
                    )}

                    {/* Ô nhập ghi chú GVCN */}
                    <div>
                      <textarea
                        rows={2}
                        value={currentNote}
                        onChange={(e) => handleNoteChange(groupId, e.target.value)}
                        placeholder={`Nhập nhận xét / lời dặn của GVCN cho Nhóm ${groupId} cuối tuần (hoặc bấm Tự động nhận xét ở trên)...`}
                        className="w-full text-xs p-2.5 bg-white border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 text-slate-900 placeholder:text-slate-400"
                      />
                    </div>

                    {/* Gợi ý mẫu nhận xét nhanh */}
                    <div className="flex items-center gap-1.5 flex-wrap pt-0.5">
                      <span className="text-[10px] text-slate-500 font-bold">Gợi ý thêm:</span>
                      {QUICK_NOTE_TEMPLATES.map((tmpl, idx) => (
                        <button
                          key={idx}
                          type="button"
                          onClick={() => handleApplyTemplate(groupId, tmpl)}
                          className="text-[10px] px-2 py-0.5 rounded-md bg-white hover:bg-emerald-50 hover:text-emerald-800 text-slate-600 border border-slate-200 hover:border-emerald-300 transition-colors cursor-pointer"
                        >
                          + {tmpl.split(' ')[0]} {tmpl.slice(2, 24)}...
                        </button>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Footer cố định ở dưới */}
          <div className="flex items-center justify-between px-5 py-3 border-t border-slate-200 bg-slate-50 shrink-0">
            <div>
              {savedSuccess && (
                <span className="text-xs text-emerald-700 font-bold flex items-center gap-1.5 animate-in fade-in">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                  Đã lưu ghi chú cho cả 6 nhóm thành công!
                </span>
              )}
            </div>

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-200 rounded-xl transition-colors cursor-pointer"
              >
                Hủy bỏ
              </button>

              {/* Nút Xanh lá cây - Green theo yêu cầu */}
              <button
                type="submit"
                className="flex items-center gap-2 px-5 py-2.5 text-xs font-bold text-white bg-emerald-600 hover:bg-emerald-500 active:bg-emerald-700 rounded-xl shadow-md shadow-emerald-950/30 border border-emerald-400/30 transition-all cursor-pointer hover:scale-[1.02]"
              >
                <Save className="w-4 h-4 text-emerald-100" />
                <span>Lưu Ghi Chú Cả 6 Nhóm</span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};
